### ISSUE TITLE
 add the option to override parameters in all relevant cmdlets

### ISSUE THREAD

**Issue by wahidsaleemi** [Ba4bes/ARMHelper#26] opened 2019-07-30 11:44 UTC
Test-ARMExistingResource fails, specifically in an Azure DevOps pipeline, if there are no existing resources. The following error is returned:
##[error]Something is wrong with the output, no resources found. 

The issue is that having no existing resources could be a valid state, for example in new deployments. The error results in the build task reporting an error and by default, won't continue on to further build tasks.

Expected behavior would be that this is a warning, not an error. If "Get-AzResource -ResourceGroupName example-rg" returns $null, we don't have an error. The error should only occur if the cmdlet reports an error. Typical errors are "Resource Group could not be found" or "User does not have access."

**Comment by Ba4bes** [comment] 2019-07-30 16:33
Awesome find! As I said, I didn't consider this scenario when creating the cmdlet.  But it's a very valid one. 
I will get into this next week.

**Comment by Ba4bes** [comment] 2019-08-15 08:13
I have looked into this, and I'm not sure if the problem is because of no existing resources, I think it is because the Resourcegroup you try to deploy to does not exist.
I have checked to reproduce. When I run Test-ARMExistingResource or Test-ARMDeploymentResource I get an error:
"Something is wrong with the output, no resources found. Please check your deployment with Get-ARMdeploymentErrorMessage"
When I run Get-ARMDeploymentErrormessage, I get:
Error, Find info below:
Resource group 'test' could not be found.

Could you confirm if you get the same output?
And does the pipeline say you should run Get-ARMDeploymentErrormessage, or just this output? 

The error message should be changed. 
But this makes this issue about the handling of non-existing resourecegroups. 
Which could go two ways: 
-  Better errorhandling
- The option to let ARMHelper create the resourcegroup for you.
 
Or both of course :)

**Comment by wahidsaleemi** [comment] 2019-08-16 01:06
It's not the lack of resource group, that's always created ahead of time so that I can deploy an ARM template right into it. The output in my build pipeline does not say to run Get-ARMdeploymentErrorMessage but I can try again with the updated ARMHelper module and report back.

**Comment by Ba4bes** [comment] 2019-08-19 14:52
If you run it manually, does it then state to run Get-ARMDeploymentErrorMessage?

**Comment by Ba4bes** [comment] 2019-08-29 19:40
This could very well be it, as I don't work with Linked templates myself. 
I want to do some testing to confirm, hope to get to it this weekend. I will get back to you as soon I can.

**Comment by Ba4bes** [comment] 2019-09-01 19:36
Alright, I have done some testing and the problem seems to be overriding parameters as you said. The module isn't able to handle that at this point. 
To fix this I want to implement overriding parameters as a feature overall. I'm working on this now.

I should say though that Test-ARMExistingResource will not work well with a linked template, as it uses Test-AzResourceGroupDeployment, which doesn't output the results of the linked template. This is something I want to look into, but will take a bit more time as it is a bit more complicated.

So to conclude, I want to create a separate issue for Test-ARMExistingResource not working with a linked template (and get started with adding a warning to the current output). 

For this issue, I will focus on adding the feature to override parameters, which should fix the initial issue.

**Comment by Ba4bes** [comment] 2019-09-05 16:30
This issue will be fixed in the next release

**Closed** 2019-09-10 13:35 UTC
